rbac:
  create: true

## Define serviceAccount names for components. Defaults to component's fully qualified name.
##
serviceAccounts:
  alertmanager:
    create: true
    name:
  kubeStateMetrics:
    create: true
    name:
  nodeExporter:
    create: true
    name:
  pushgateway:
    create: true
    name:
  server:
    create: true
    name:
    extraArgs:
    - --storage.tsdb.retention=15d
    - --storage.tsdb.max-block-duration=2h
    sidecarContainers:
    - name: thanos-sidecar
      # Always use explicit image tags (release or master-<date>-sha) instead of ambigous `latest` or `master`.
      image: quay.io/thanos/thanos:v0.7.0
      args:
      - "sidecar"
      - "--log.level=debug"
      - "--tsdb.path=/data/"
      - "--prometheus.url=http://127.0.0.1:9090"
      - "--cluster.disable"
      - "--objstore.config-file=/etc/config/azure-storage.yml"
      - "--reloader.config-file=/etc/prometheus-config/prometheus.yml"
      - "--reloader.config-envsubst-file=/etc/prometheus-shared/prometheus.yml"
      - "--reloader.rule-dir=/etc/prometheus-config/rules"
      ports:
      - name: sidecar-http
        containerPort: 10902
      - name: grpc
        containerPort: 10901
      - name: cluster
        containerPort: 10900
      volumeMounts:
      - mountPath: /etc/config
        name: config-volume
      - name: storage-volume
        mountPath: /data
      - name: thanos-storage-secret
        mountPath: /etc/secret
      - name: config-volume
        mountPath: /etc/prometheus-config
        readOnly: false
      - name: prometheus-config-shared
        mountPath: /etc/prometheus-shared/
        readOnly: false
    configPath: /etc/prometheus-shared/prometheus.yml
    replicaCount: 2
    persistentVolume:
      size: 100Gi
    extraVolumes:
    - name: prometheus-config-shared
      emptyDir: {}
    - name: config-volume
      configMap:
        defaultMode: 420
        name: thanos-storage-zwindlerk8s
    extraVolumeMounts:
    - name: prometheus-config-shared
      mountPath: /etc/prometheus-shared/
    resources:
      limits:
        cpu: 4
        memory: 20Gi
      requests:
        cpu: 4
        memory: 20Gi
    global:
      scrape_interval: 5s
      scrape_timeout: 4s
      external_labels:
        prometheus_group: zwindlerk8s
        prometheus_replica: '$(HOSTNAME)'
      evaluation_interval: 5s
    extraSecretMounts:
    - name: thanos-storage-secret
      mountPath: /etc/secret/
      subPath: sa
      readOnly: false
      secretName: thanos-storage-secret