rbac:
  create: true

## Define serviceAccount names for components. Defaults to component's fully qualified name.
##
serviceAccounts:
  alertmanager:
    create: true
  kubeStateMetrics:
    create: true
  nodeExporter:
    create: true
  pushgateway:
    create: true

server:
  create: true
  extraArgs:
    storage.tsdb.retention: 15d
    storage.tsdb.max-block-duration: 2h
  sidecarContainers:
  - name: thanos-sidecar
    # Always use explicit image tags (release or master-<date>-sha) instead of ambigous `latest` or `master`.
    image: quay.io/thanos/thanos:v0.7.0
    args:
    - "sidecar"
    - "--log.level=debug"
    - "--tsdb.path=/data/"
    - "--prometheus.url=http://127.0.0.1:9090"
    - "--objstore.config-file=/etc/thanos-config/azure-storage.yml"
    ports:
    - name: sidecar-http
      containerPort: 10902
    - name: grpc
      containerPort: 10901
    - name: cluster
      containerPort: 10900
    volumeMounts:
    - name: storage-volume
      mountPath: /data
    - name: config-volume
      mountPath: /etc/prometheus-config
      readOnly: false
    - name: thanos-config-volume
      mountPath: /etc/thanos-config    
  global:
    scrape_interval: 5s
    scrape_timeout: 4s
    external_labels:
      prometheus_group: zwindlerk8s
      prometheus_replica: '$(HOSTNAME)'
    evaluation_interval: 5s
  extraVolumes:
  - configMap:
      defaultMode: 420
      name: thanos-storage-zwindlerk8s
    name: thanos-config-volume
  extraVolumeMounts:
  - name: thanos-config-volume
    mountPath: /etc/thanos-config
